version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/starter-engine
    docker:
      - image: circleci/node:8.11.3
    steps: # a collection of executable commands
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install -save-dev jest-stare
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test -- --ci --runInBand --testResultsProcessor="jest-stare" --coverage
          environment:
            JEST_STARE_RESULT_DIR: "reports/jest-stare"
            JEST_STARE_COVERAGE_LINK: "../lcov-report/index.html"
      - store_test_results:
          path: reports/jest-stare
      - store_artifacts:
          path: reports/jest-stare
      - store_artifacts:
          path: reports/lcov-report
      - run:
          name: Pack
          command: npm pack
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
