version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/starter-engine
    docker:
      - image: circleci/node:4.8.2
    steps: # a collection of executable commands
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Pack
          command: npm pack
      - persist_to_workspace:
          root: ~/starter-engine
          paths: ./reports
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
