version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/starter-engine
    docker:
      - image: circleci/node:8.11.3
    steps: # a collection of executable commands
      - checkout
      - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
      - run:
        name: Install
        command: npm install
      - run:
        Install JUnit coverage reporter
        npm install -save-dev jest-junit
      - run:
        name: Lint
        command: npm run lint
      - run:
        name: Test
        command: npm test
      - store_test_results:
        path: reports
      - run:
        name: Pack
        command: npm pack
      - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
          - ./node_modules
