version: 2 # use CircleCI 2.0
jobs:
  build:
    working_directory: ~/starter-engine
    docker:
      - image: circleci/node:8.11.3
    steps: # a collection of executable commands
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install
          command: npm install
      - run:
          name: Install JUnit coverage reporter
          command: npm install -save-dev jest-junit
      - run:
          name: Lint
          command: npm run lint --format junit -o reports/junit/lint-results.xml
      - run:
          name: Test
          command: npm test -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/test-results.xml"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Pack
          command: npm pack
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
